FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD target/Cmpe202-Starbucks-0.0.1-SNAPSHOT.jar Cmpe202-Starbucks-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/Cmpe202-Starbucks-0.0.1-SNAPSHOT.jar"]